/**
 * Server Portal Routes — /api/server/*
 *
 * Authentication: servers log in with their 4-digit PIN via:
 *   POST /api/server/login  { slug, pin }
 * The response contains a short-lived server JWT (8h).
 * All other routes require this token in Authorization: Bearer <token>.
 */
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { prisma } from "../db.js";
import { env } from "../env.js";
import { emitToRestaurant } from "../realtime.js";
import { getGlobalIaConfig, callCloudAI } from "../globalIaConfig.js";
import jwt from "jsonwebtoken";

type ServerJwtPayload = { serverId: string; restaurantId: string };

// ── Auto-generate daily challenges ────────────────────────────────────────────
// Called at every server login. Creates global challenges once per day per restaurant
// using real context: server names, top menu items, day of week.
async function autoGenerateDailyChallenges(
  restaurantId: string,
  serverId: string,
  restaurantName: string,
  subscription: string
) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1);

  // Already generated today?
  const existing = await prisma.serverChallenge.findFirst({
    where: { restaurantId, isGlobal: true, createdAt: { gte: today, lt: tomorrow } },
  });
  if (existing) return;

  // Fetch context: servers + menu items
  const [servers, menuItems] = await Promise.all([
    prisma.server.findMany({ where: { restaurantId, active: true }, select: { id: true, name: true } }),
    prisma.menuItem.findMany({ where: { restaurantId, available: true }, select: { name: true, priceCents: true, category: true }, take: 15 }),
  ]);

  if (servers.length === 0) return;

  const dayLabel = new Date().toLocaleDateString("fr-FR", { weekday: "long", day: "numeric", month: "long" });
  const serverNames = servers.map(s => s.name).join(", ");
  const menuSample = menuItems.slice(0, 8).map(i => `${i.name} (${(i.priceCents / 100).toFixed(0)}€)`).join(", ");

  let challengeTitles: string[] = [];

  // Try global IA config
  if (subscription === "PRO_IA") {
    try {
      const iaConfig = await getGlobalIaConfig();
      if (iaConfig.ollamaApiKey) {
        const prompt = `Tu es un chef de salle qui crée des défis quotidiens pour ses serveurs.
Aujourd'hui : ${dayLabel} — Restaurant "${restaurantName}"
Serveurs en compétition : ${serverNames}
Menu du jour (extraits) : ${menuSample || "menu varié"}

Génère exactement 3 défis compétitifs, mesurables, fun et réalisables en service.
Chaque défi doit impliquer un produit ou comportement spécifique à ce restaurant.
Format : 3 lignes uniquement, sans numéro, sans tiret.`;

        const text = await callCloudAI(iaConfig, prompt, 200);
        challengeTitles = text
          .split("\n")
          .map((l: string) => l.trim().replace(/^[-•*\d.]\s*/, ""))
          .filter((l: string) => l.length > 8)
          .slice(0, 3);
      }
    } catch { /* fallback below */ }
  }

  // Fallback: curated smart challenges using menu items
  if (challengeTitles.length < 3) {
    const topItems = menuItems.filter(i => i.priceCents > 1500).slice(0, 2).map(i => i.name);
    const fallbacks = [
      topItems[0] ? `Vendre ${topItems[0]} à au moins 2 tables` : "Proposer un dessert à chaque table et en vendre au moins 3",
      topItems[1] ? `Recommander ${topItems[1]} en plat principal` : "Obtenir 2 retours positifs spontanés de clients",
      "Mémoriser et expliquer 5 plats du menu sans consulter la carte",
      "Proposer une boisson d'accord avec chaque plat commandé",
    ];
    while (challengeTitles.length < 3) challengeTitles.push(fallbacks[challengeTitles.length]);
  }

  // Create one challenge per server
  const dueDate = tomorrow;
  const { randomUUID } = await import("crypto");
  const createData = servers.flatMap(s =>
    challengeTitles.map(title => ({
      id: randomUUID(),
      serverId: s.id,
      title,
      isGlobal: true,
      restaurantId,
      dueDate,
      done: false,
      createdAt: new Date(),
    }))
  );

  if (createData.length > 0) {
    await prisma.serverChallenge.createMany({ data: createData });
  }
}

function signServerToken(payload: ServerJwtPayload): string {
  return jwt.sign(payload, env.JWT_SECRET, { expiresIn: "8h" });
}

async function requireServer(req: any, reply: any): Promise<ServerJwtPayload> {
  const auth = req.headers?.authorization as string | undefined;
  if (!auth?.startsWith("Bearer ")) {
    reply.code(401).send({ error: "UNAUTHORIZED" });
    throw new Error("Unauthorized");
  }
  try {
    return jwt.verify(auth.slice(7), env.JWT_SECRET) as ServerJwtPayload;
  } catch {
    reply.code(401).send({ error: "INVALID_TOKEN" });
    throw new Error("Invalid token");
  }
}

export async function serverPortalRoutes(app: FastifyInstance) {
  const authRateLimit = { config: { rateLimit: { max: 10, timeWindow: "1 minute" } } };

  // ── POST /api/server/login ─────────────────────────────────────────────────
  app.post("/login", authRateLimit, async (req, reply) => {
    const { slug, pin } = z.object({
      slug: z.string(),
      pin: z.string().min(4).max(6),
    }).parse(req.body);

    const restaurant = await prisma.restaurant.findUnique({
      where: { slug },
      select: { id: true, name: true, subscription: true },
    });
    if (!restaurant) return reply.code(404).send({ error: "RESTAURANT_NOT_FOUND" });

    const server = await prisma.server.findFirst({
      where: { restaurantId: restaurant.id, pin, active: true },
    });
    if (!server) return reply.code(401).send({ error: "INVALID_PIN" });

    const token = signServerToken({ serverId: server.id, restaurantId: restaurant.id });

    // Auto-generate daily challenges on login (non-blocking, best-effort)
    autoGenerateDailyChallenges(restaurant.id, server.id, restaurant.name, restaurant.subscription).catch(() => {});

    return {
      token,
      server: { id: server.id, name: server.name, photoUrl: server.photoUrl },
      restaurant: { id: restaurant.id, name: restaurant.name, subscription: restaurant.subscription },
    };
  });

  // ── GET /api/server/me ─────────────────────────────────────────────────────
  app.get("/me", async (req, reply) => {
    const me = await requireServer(req, reply);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1);

    const [server, restaurant, globalChallenges] = await Promise.all([
      prisma.server.findUnique({
        where: { id: me.serverId },
        include: {
          schedules: { orderBy: [{ dayOfWeek: "asc" }] },
          notes: { orderBy: { updatedAt: "desc" }, take: 20 },
          challenges: {
            where: { isGlobal: false },
            orderBy: { createdAt: "desc" },
          },
        },
      }),
      prisma.restaurant.findUnique({
        where: { id: me.restaurantId },
        select: { name: true, subscription: true },
      }),
      // Global AI challenges generated today for this restaurant
      prisma.serverChallenge.findMany({
        where: {
          serverId: me.serverId,
          isGlobal: true,
          createdAt: { gte: today, lt: tomorrow },
        },
        orderBy: { createdAt: "asc" },
      }),
    ]);

    if (!server) return reply.code(404).send({ error: "NOT_FOUND" });
    return { server: { ...server, globalChallenges }, restaurant };
  });

  // ── GET /api/server/tables ─────────────────────────────────────────────────
  // Returns:
  //   sessions    → ALL active sessions of the restaurant (not just mine)
  //                 Sessions assigned to me come first, unassigned second.
  //                 This way servers see orders even when no serverId is set.
  //   allTables   → All tables with their active session state
  //   myEmptyTables → Tables assigned to me with no active session
  app.get("/tables", async (req, reply) => {
    const me = await requireServer(req, reply);

    // All active sessions for the entire restaurant — sorted: mine first, then unassigned, then others
    const allSessions = await prisma.tableSession.findMany({
      where: { table: { restaurantId: me.restaurantId }, active: true },
      include: {
        table: { select: { id: true, number: true, seats: true } },
        orders: {
          where: { status: { in: ["PENDING", "COOKING", "SERVED"] } },
          orderBy: { createdAt: "desc" },
        },
        server: { select: { id: true, name: true } },
      },
      orderBy: { createdAt: "asc" },
    });

    // Attach bill + split fields via raw query (added via ensure_columns.sql)
    type BillRow = {
      id: string;
      billPaymentMode: string | null;
      billRequestedAt: Date | null;
      billConfirmedAt: Date | null;
      billConfirmedBy: string | null;
      billSplits: any;
      tipCents: number;
    };
    const sessionIds = allSessions.map((s) => s.id);
    let billRows: BillRow[] = [];
    if (sessionIds.length > 0) {
      billRows = await prisma.$queryRaw<BillRow[]>`
        SELECT id, "billPaymentMode", "billRequestedAt", "billConfirmedAt", "billConfirmedBy",
               COALESCE("billSplits", '[]'::jsonb) AS "billSplits",
               COALESCE("tipCents", 0) AS "tipCents"
        FROM "TableSession"
        WHERE id = ANY(${sessionIds}::text[])
      `;
    }
    const billMap = new Map(billRows.map((r) => [r.id, r]));
    const allSessionsWithBill = allSessions.map((s) => {
      const b = billMap.get(s.id);
      const orders = s.orders as any[];
      const subtotalCents = orders.reduce((sum: number, o: any) => sum + o.totalCents, 0);
      const tipCents = b?.tipCents ?? 0;
      return {
        ...s,
        subtotalCents,
        tipCents,
        totalCents: subtotalCents + tipCents,
        billPaymentMode: b?.billPaymentMode ?? null,
        billRequestedAt: b?.billRequestedAt ?? null,
        billConfirmedAt: b?.billConfirmedAt ?? null,
        billConfirmedBy: b?.billConfirmedBy ?? null,
        billSplits: Array.isArray(b?.billSplits) ? b!.billSplits : [],
      };
    });

    // Sort: mine first, unassigned second, others last
    const sessions = allSessionsWithBill.sort((a, b) => {
      const aMine = a.serverId === me.serverId ? 0 : a.serverId === null ? 1 : 2;
      const bMine = b.serverId === me.serverId ? 0 : b.serverId === null ? 1 : 2;
      return aMine - bMine;
    });

    // All tables of the restaurant with session state
    const allTables = await prisma.table.findMany({
      where: { restaurantId: me.restaurantId },
      include: {
        sessions: {
          where: { active: true },
          take: 1,
          include: { server: { select: { id: true, name: true } } },
        },
      },
      orderBy: { number: "asc" },
    });

    // My assigned empty tables (no active session yet but table is mine by default)
    const activeSessionTableIds = new Set(sessions.map((s) => s.tableId));
    const myEmptyTables = allTables.filter(
      (t) => (t as any).assignedServerId === me.serverId && !activeSessionTableIds.has(t.id)
    );

    return { sessions, allTables, myEmptyTables };
  });

  // ── POST /api/server/tables/:sessionId/claim ──────────────────────────────
  // Server claims an unassigned (or reassignable) session
  app.post("/tables/:sessionId/claim", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { sessionId } = req.params as { sessionId: string };

    const session = await prisma.tableSession.findFirst({
      where: { id: sessionId, table: { restaurantId: me.restaurantId }, active: true },
    });
    if (!session) return reply.code(404).send({ error: "SESSION_NOT_FOUND" });

    const updated = await prisma.tableSession.update({
      where: { id: sessionId },
      data: { serverId: me.serverId },
    });
    return { ok: true, session: updated };
  });

  // ── POST /api/server/tables/:sessionId/bill-confirm ─────────────────────────
  // Server confirms they've brought the bill/TPE to the table
  app.post("/tables/:sessionId/bill-confirm", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { sessionId } = req.params as { sessionId: string };

    const server = await prisma.server.findUnique({
      where: { id: me.serverId },
      select: { name: true },
    });
    if (!server) return reply.code(404).send({ error: "SERVER_NOT_FOUND" });

    const session = await prisma.tableSession.findFirst({
      where: { id: sessionId, table: { restaurantId: me.restaurantId }, active: true },
      include: { table: { select: { number: true } } },
    });
    if (!session) return reply.code(404).send({ error: "SESSION_NOT_FOUND" });

    await prisma.$executeRaw`
      UPDATE "TableSession"
      SET "billConfirmedAt" = ${new Date()}, "billConfirmedBy" = ${server.name}
      WHERE id = ${sessionId}
    `;

    // Emit to caisse + all connected staff
    emitToRestaurant(me.restaurantId, "bill:confirmed", {
      sessionId,
      tableNumber: session.table.number,
      serverName: server.name,
    });

    return { ok: true, serverName: server.name };
  });

  // ── POST /api/server/tables/:sessionId/close ─────────────────────────────
  // Server closes the session (same logic as caisse)
  app.post("/tables/:sessionId/close", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { sessionId } = req.params as { sessionId: string };
    const { paymentMode } = z.object({
      paymentMode: z.enum(["CARD", "CASH", "COUNTER"]).default("CARD"),
    }).parse(req.body ?? {});

    const session = await prisma.tableSession.findFirst({
      where: { id: sessionId, table: { restaurantId: me.restaurantId }, active: true },
    });
    if (!session) return reply.code(404).send({ error: "SESSION_NOT_FOUND" });

    await prisma.$transaction([
      prisma.order.updateMany({
        where: { sessionId, status: { in: ["PENDING", "COOKING", "SERVED"] } },
        data: { status: "PAID" },
      }),
      prisma.tableSession.update({
        where: { id: sessionId },
        data: { active: false, closedAt: new Date(), billPaymentMode: paymentMode },
      }),
    ]);

    emitToRestaurant(me.restaurantId, "order:paid", { sessionId });
    return { ok: true };
  });

  // ── PUT /api/server/tables/:sessionId/splits ──────────────────────────────
  // Define split parts for a session
  app.put("/tables/:sessionId/splits", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { sessionId } = req.params as { sessionId: string };

    const splitSchema = z.array(z.object({
      id: z.string(),
      label: z.string().min(1).max(50),
      amountCents: z.number().int().min(0),
      paid: z.boolean().default(false),
      paidAt: z.string().optional().nullable(),
      paymentMode: z.enum(["CARD", "CASH", "COUNTER"]).optional().nullable(),
    })).min(2).max(20);

    const splits = splitSchema.parse(req.body);

    const session = await prisma.tableSession.findFirst({
      where: { id: sessionId, table: { restaurantId: me.restaurantId }, active: true },
    });
    if (!session) return reply.code(404).send({ error: "SESSION_NOT_FOUND" });

    await prisma.$executeRaw`
      UPDATE "TableSession" SET "billSplits" = ${JSON.stringify(splits)}::jsonb WHERE id = ${sessionId}
    `;

    emitToRestaurant(me.restaurantId, "splits:updated", { sessionId, splits });
    return { ok: true, splits };
  });

  // ── PATCH /api/server/tables/:sessionId/splits/:splitId/pay ──────────────
  // Mark one split as paid; auto-close session if all splits are paid
  app.patch("/tables/:sessionId/splits/:splitId/pay", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { sessionId, splitId } = req.params as { sessionId: string; splitId: string };
    const { paymentMode } = z.object({
      paymentMode: z.enum(["CARD", "CASH", "COUNTER"]).default("CARD"),
    }).parse(req.body ?? {});

    type SplitRow = { id: string; billSplits: any };
    const rows = await prisma.$queryRaw<SplitRow[]>`
      SELECT id, COALESCE("billSplits", '[]'::jsonb) AS "billSplits"
      FROM "TableSession" WHERE id = ${sessionId}
        AND active = true
    `;
    if (rows.length === 0) return reply.code(404).send({ error: "SESSION_NOT_FOUND" });

    const splits: any[] = Array.isArray(rows[0].billSplits) ? rows[0].billSplits : [];
    const idx = splits.findIndex((s: any) => s.id === splitId);
    if (idx === -1) return reply.code(404).send({ error: "SPLIT_NOT_FOUND" });

    splits[idx] = { ...splits[idx], paid: true, paidAt: new Date().toISOString(), paymentMode };

    await prisma.$executeRaw`
      UPDATE "TableSession" SET "billSplits" = ${JSON.stringify(splits)}::jsonb WHERE id = ${sessionId}
    `;

    const allPaid = splits.every((s: any) => s.paid);

    if (allPaid) {
      // Auto-close: mark all orders PAID and close session
      await prisma.$transaction([
        prisma.order.updateMany({
          where: { sessionId, status: { in: ["PENDING", "COOKING", "SERVED"] } },
          data: { status: "PAID" },
        }),
        prisma.tableSession.update({
          where: { id: sessionId },
          data: { active: false, closedAt: new Date(), billPaymentMode: paymentMode },
        }),
      ]);
      emitToRestaurant(me.restaurantId, "order:paid", { sessionId });
    } else {
      emitToRestaurant(me.restaurantId, "splits:updated", { sessionId, splits });
    }

    return { ok: true, splits, allPaid };
  });

  // ── GET /api/server/stats ──────────────────────────────────────────────────
  app.get("/stats", async (req, reply) => {
    const me = await requireServer(req, reply);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const [ordersToday, reviews, tips] = await Promise.all([
      prisma.order.count({
        where: { serverId: me.serverId, createdAt: { gte: today } },
      }),
      prisma.serverReview.aggregate({
        where: { serverId: me.serverId },
        _avg: { rating: true },
        _count: { _all: true },
      }),
      prisma.tableSession.aggregate({
        where: { serverId: me.serverId, active: false, closedAt: { gte: today } },
        _sum: { tipCents: true },
      }),
    ]);

    return {
      ordersToday,
      avgRating: reviews._avg.rating,
      totalReviews: reviews._count._all,
      tipsToday: tips._sum.tipCents ?? 0,
    };
  });

  // ── Notes CRUD ─────────────────────────────────────────────────────────────
  app.post("/notes", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { content } = z.object({ content: z.string().min(1).max(2000) }).parse(req.body);
    const note = await prisma.serverNote.create({
      data: { serverId: me.serverId, content },
    });
    return { note };
  });

  app.patch("/notes/:id", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { id } = req.params as { id: string };
    const { content } = z.object({ content: z.string().min(1).max(2000) }).parse(req.body);
    const note = await prisma.serverNote.updateMany({
      where: { id, serverId: me.serverId },
      data: { content },
    });
    return { note };
  });

  app.delete("/notes/:id", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { id } = req.params as { id: string };
    await prisma.serverNote.deleteMany({ where: { id, serverId: me.serverId } });
    return { ok: true };
  });

  // ── Challenges CRUD ────────────────────────────────────────────────────────
  app.post("/challenges", async (req, reply) => {
    const me = await requireServer(req, reply);
    const body = z.object({
      title: z.string().min(1).max(200),
      dueDate: z.string().optional(),
    }).parse(req.body);
    const challenge = await prisma.serverChallenge.create({
      data: {
        serverId: me.serverId,
        title: body.title,
        dueDate: body.dueDate ? new Date(body.dueDate) : null,
      },
    });
    return { challenge };
  });

  app.patch("/challenges/:id/toggle", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { id } = req.params as { id: string };
    const existing = await prisma.serverChallenge.findFirst({ where: { id, serverId: me.serverId } });
    if (!existing) return reply.code(404).send({ error: "NOT_FOUND" });
    const updated = await prisma.serverChallenge.update({
      where: { id },
      data: { done: !existing.done },
    });
    return { challenge: updated };
  });

  app.delete("/challenges/:id", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { id } = req.params as { id: string };
    await prisma.serverChallenge.deleteMany({ where: { id, serverId: me.serverId } });
    return { ok: true };
  });

  // ── AI Daily Challenges — generate for all servers (PRO_IA only) ──────────
  // Generates 3 competitive cross-server challenges once per day
  app.post("/challenges/generate-daily", async (req, reply) => {
    const me = await requireServer(req, reply);

    const restaurant = await prisma.restaurant.findUnique({
      where: { id: me.restaurantId },
      select: { name: true, subscription: true, ollamaApiKey: true, ollamaLangModel: true },
    });

    if (!restaurant || restaurant.subscription !== "PRO_IA") {
      return reply.code(403).send({ error: "IA_NOT_SUBSCRIBED" });
    }

    // Check if already generated today
    const today = new Date(); today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1);
    const existing = await prisma.serverChallenge.findFirst({
      where: { restaurantId: me.restaurantId, isGlobal: true, createdAt: { gte: today, lt: tomorrow } },
    });
    if (existing) {
      // Already generated — just return today's challenges for this server
      const challenges = await prisma.serverChallenge.findMany({
        where: { serverId: me.serverId, isGlobal: true, createdAt: { gte: today, lt: tomorrow } },
      });
      return { challenges, alreadyGenerated: true };
    }

    // Get all active servers
    const servers = await prisma.server.findMany({
      where: { restaurantId: me.restaurantId, active: true },
      select: { id: true, name: true },
    });

    // Generate challenges via global IA config
    let challengeTitles: string[] = [];
    try {
      const iaConfig = await getGlobalIaConfig();
      if (iaConfig.ollamaApiKey) {
        const today_label = new Date().toLocaleDateString("fr-FR", { weekday: "long", day: "numeric", month: "long" });
        const prompt = `Tu es un chef de salle qui organise des défis quotidiens entre serveurs pour maintenir la motivation.
Aujourd'hui c'est ${today_label} au restaurant "${restaurant.name}".
Génère exactement 3 défis de service compétitifs, originaux et mesurables pour la journée.
Format: retourne UNIQUEMENT 3 lignes, une par défi, sans numérotation, sans explication.`;
        const text = await callCloudAI(iaConfig, prompt, 200);
        challengeTitles = text
          .split("\n")
          .map((l: string) => l.trim().replace(/^[-•*\d.]\s*/, ""))
          .filter((l: string) => l.length > 5)
          .slice(0, 3);
      }
    } catch {}

    // Fallback challenges if AI unavailable
    if (challengeTitles.length < 3) {
      const fallbacks = [
        "Proposer un dessert à chaque table — vendre au moins 3 desserts",
        "Obtenir 2 compliments spontanés de clients",
        "Mémoriser et réciter la composition de 5 plats sans consulter la carte",
      ];
      while (challengeTitles.length < 3) challengeTitles.push(fallbacks[challengeTitles.length]);
    }

    // Create one challenge per server per title
    const dueDate = tomorrow;
    const createData = servers.flatMap((server) =>
      challengeTitles.map((title) => ({
        id: require("crypto").randomUUID(),
        serverId: server.id,
        title,
        isGlobal: true,
        restaurantId: me.restaurantId,
        dueDate,
        done: false,
        createdAt: new Date(),
      }))
    );
    await prisma.serverChallenge.createMany({ data: createData });

    // Return this server's challenges
    const myChallenges = createData.filter((c) => c.serverId === me.serverId);
    return { challenges: myChallenges, alreadyGenerated: false };
  });

  // ── GET /api/server/menu ──────────────────────────────────────────────────
  // Returns all available menu items for the restaurant (for server ordering on behalf)
  app.get("/menu", async (req, reply) => {
    const me = await requireServer(req, reply);
    // Fetch via raw to include waitMinutes (added via ensure_columns.sql, not in Prisma schema)
    type MenuItemRow = { id: string; name: string; description: string | null; priceCents: number; category: string | null; waitMinutes: number };
    const items = await prisma.$queryRaw<MenuItemRow[]>`
      SELECT id, name, description, "priceCents", category, COALESCE("waitMinutes", 0) AS "waitMinutes"
      FROM "MenuItem"
      WHERE "restaurantId" = ${me.restaurantId} AND available = true
      ORDER BY category ASC, name ASC
    `;
    return { items };
  });

  // ── POST /api/server/tables/:tableId/place-order ───────────────────────────
  // Server places an order on behalf of a customer who didn't use the QR code.
  // Creates a session automatically if no active one exists for that table.
  app.post("/tables/:tableId/place-order", async (req, reply) => {
    const me = await requireServer(req, reply);
    const { tableId } = req.params as { tableId: string };

    const body = z.object({
      items: z.array(z.object({
        menuItemId: z.string(),
        quantity: z.number().int().min(1).max(50),
      })).min(1).max(50),
      notes: z.string().max(500).optional(),
    }).parse(req.body);

    // Verify table belongs to restaurant
    const table = await prisma.table.findFirst({
      where: { id: tableId, restaurantId: me.restaurantId },
      select: { id: true, number: true },
    });
    if (!table) return reply.code(404).send({ error: "TABLE_NOT_FOUND" });

    // Fetch menu items to validate + compute total
    // Use raw query to include waitMinutes (not in Prisma schema)
    const menuItemIds = body.items.map((i) => i.menuItemId);
    type ValidatedItem = { id: string; name: string; priceCents: number; waitMinutes: number };
    const menuItems = await prisma.$queryRaw<ValidatedItem[]>`
      SELECT id, name, "priceCents", COALESCE("waitMinutes", 0) AS "waitMinutes"
      FROM "MenuItem"
      WHERE id = ANY(${menuItemIds}::text[])
        AND "restaurantId" = ${me.restaurantId}
        AND available = true
    `;
    if (menuItems.length !== menuItemIds.length) {
      return reply.code(400).send({ error: "SOME_ITEMS_UNAVAILABLE" });
    }

    const menuMap = new Map(menuItems.map((m) => [m.id, m]));

    // Build order items
    const orderItems = body.items.map((i) => {
      const m = menuMap.get(i.menuItemId)!;
      return { menuItemId: m.id, name: m.name, quantity: i.quantity, priceCents: m.priceCents };
    });
    const totalCents = orderItems.reduce((s, i) => s + i.priceCents * i.quantity, 0);
    const maxWait = Math.max(...menuItems.map((m) => m.waitMinutes ?? 0));

    const { randomUUID } = await import("crypto");

    // Find or create active session for this table
    let session = await prisma.tableSession.findFirst({
      where: { tableId, active: true },
    });
    if (!session) {
      // Create a server-initiated session (no QR token needed)
      session = await prisma.tableSession.create({
        data: {
          tableId,
          active: true,
          serverId: me.serverId,
        },
      });
    }

    // Create the order
    const orderId = randomUUID();
    const expectedReadyAt = maxWait > 0 ? new Date(Date.now() + maxWait * 60_000) : null;
    await prisma.order.create({
      data: {
        id: orderId,
        tableId,
        sessionId: session.id,
        serverId: me.serverId,
        status: "PENDING",
        items: orderItems as any,
        totalCents,
        notes: body.notes ?? null,
      },
    });
    // Update expectedReadyAt via raw SQL (column added via ensure_columns.sql, not in Prisma schema)
    if (expectedReadyAt) {
      await prisma.$executeRaw`
        UPDATE "Order" SET "expectedReadyAt" = ${expectedReadyAt} WHERE id = ${orderId}
      `;
    }

    // Emit socket event
    emitToRestaurant(me.restaurantId, "order:new", {
      orderId,
      tableId,
      tableNumber: table.number,
      sessionId: session.id,
      items: orderItems,
      totalCents,
      source: "server",
    });

    return { ok: true, orderId, sessionId: session.id, totalCents };
  });

  // ── IA Planning Suggestion (PRO_IA only) ──────────────────────────────────
  app.post("/ia/planning-suggest", async (req, reply) => {
    const me = await requireServer(req, reply);

    const restaurant = await prisma.restaurant.findUnique({
      where: { id: me.restaurantId },
      select: { subscription: true, name: true },
    });

    if (!restaurant || restaurant.subscription !== "PRO_IA") {
      return reply.code(403).send({ error: "IA_NOT_SUBSCRIBED" });
    }

    const iaConfig = await getGlobalIaConfig();
    if (!iaConfig.ollamaApiKey) {
      return reply.code(503).send({ error: "IA_KEY_MISSING" });
    }

    const { context, currentPlanning } = z.object({
      context: z.string().max(500),
      currentPlanning: z.string().max(2000).optional(),
    }).parse(req.body);

    const server = await prisma.server.findUnique({
      where: { id: me.serverId },
      select: { name: true },
    });

    const prompt = `Tu es un assistant pour un serveur en restaurant nommé ${server?.name ?? "serveur"}.
Voici le contexte/retour client du serveur : "${context}"
${currentPlanning ? `Planning actuel : ${currentPlanning}` : ""}
Génère 2-3 suggestions concrètes d'amélioration du planning ou des plats du jour basées sur ce retour terrain.
Réponds de façon concise en français, en bullet points.`;

    try {
      const suggestions = await callCloudAI(iaConfig, prompt, 400);
      return { suggestions };
    } catch (err: any) {
      return reply.code(500).send({ error: "AI_SERVICE_UNAVAILABLE" });
    }
  });
}
